networks:
  gestion-dossiers-patients_net:
    driver: bridge

services:
  dev-db:
    image: mysql:8.1
    container_name: dossiers_patients_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3310:3306"
    networks:
      - gestion-dossiers-patients_net
    volumes:
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - dev-db_data:/var/lib/mysql
    
  adminer:
    image: adminer
    container_name: adminer_gestion-dossiers-patients
    restart: always
    ports:
      - "8010:8080"
    environment:
      ADMINER_DEFAULT_SERVER: dev-db
    networks:
      - gestion-dossiers-patients_net

volumes:
  dev-db_data: